### ISSUE TITLE
preCreateIdentityCallback and preEnableIdentityCallback

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#109]
Add `preCreateIdentityCallback` and `preEnableIdentityCallback` that we use during the onboarding from the JS SDK

Will likely need updates to iOS and Android.

**Comment by nmalzieu** [comment]
@nplasterer Adding this here since to us it's linked to the onboarding!
Right now the RN SDK the `canMessage` method is only available on the client instance i.e. after having connected. But during onboarding we check if the current wallet is on XMTP to change the UX, so would be nice to have `canMessage` accessible directly on the `Client` class (with parameter for the network)

**Comment by Kalas777** [comment]
👍🦺
