### ISSUE TITLE
Rust detect connection loss

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#129]
When the iOS swift bridge looses a connection with Rust it does not try again or notify that the connection was lost

**Comment by richardhuaaa** [comment]
Noe's notes:
> So I have done tests and I can only reproduce on device - trying to disable connection with the network link conditioner in the ios simulator was not enough to reproduce
Here is a repo that reproduces it : https://github.com/nmalzieu/xmtp-rust-connection
Run on device, click “List Conversations” once : it will create a client and list conversations very fast. You can do it multiple times, always very fast
Then activate airplane mode : “Internet reachable:” will say NO
The disable airplane mode : “Internet reachable:” will say YES
Now click “List Conversations” again and it will take > 1 min

> If I just re-instantitate a new client after airplane mode is off, it works well. So it’s really the “old” client instantiated before the disconnect that’s “broken”.
On mobile there are often small disconnections so this is a big deal for us - we can just reinstantiate the client for now but that’s if we’re able to detect the disconnect which is not 100% of the time!
By adding some logs & breakpoints the issue lies here:
https://github.com/xmtp/xmtp-rust-swift/blob/main/Sources/XMTPRust/xmtp_rust_swift.swift#L213
so I guess the issue is directly in the Rust lib?

What I found is it only reproduces on cellular network on device, not on Wifi. That's probably why it doesn't repro on simulator.

Tried:
- Modifying the repro code to retry on a 10s interval - the retry was still slow
- Tried to add a retry in the Rust networking library: https://github.com/xmtp/libxmtp/pull/255. Didn't work, but I suspect the method I'm using here relies on the server responding to a flag, rather than the client natively retrying/resetting networking state
- Tried googling for similar issues in Tonic/hyper

Ideas:
- Currently there is no way to log anything in Rust and see those logs when running in React Native, so there's no real feedback as to what's happening in Rust. I'm thinking I can implement this by passing a logging callback down from iOS into Rust in v2, but it will take a while to implement
  - This would be helpful, for example, to see if it's our own client code or server code deadlocking, or if it is indeed inside of Tonic/hyper
- Build a minimal Rust repro with Tonic/hyper without any of our application logic
- Manually reset the tonic networking client inside Rust after a request takes too long. Avoiding this for now because if there are multiple requests in flight we would probably drop the other ones.

**Comment by richardhuaaa** [comment]
I've started a minimal Rust repro with `hyper`. Will convert it into a library and plumb it through to React Native tomorrow (https://github.com/xmtp/libxmtp/compare/v2...rich/simple_hyper?expand=1). If it reproduces, I can file a bug on hyper, if not, I can keep adding `tonic`/`libxmtp` code back in until it reproduces.

**Comment by neekolas** [comment]
@richardhuaaa one thing worth testing once you have the minimal repro up is fiddling with the `http2_keep_alive_interval`. Hyper defaults it to `None`, which turns off keep-alive pings.

**Comment by richardhuaaa** [comment]
The timeout fix above is working. Copying from our conversation with Noe:

> Our working theory is that there is a persistent http/2 connection that is broken after airplane mode is turned off and then on. In the Wifi case, both the native Android and the Rust library pick up that the connection state has changed, and close the connection immediately. In the cellular disconnect case, Android can detect this immediately but Rust cannot detect it until the keepalive ping fails. It's unclear if the mechanism Android uses is just the same keepalive with a shorter timeout, or if there's some native notification mechanism that the Rust implementation is not using yet.
