### ISSUE TITLE
Bug: Case Insensitive Address Checks

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#230]
### Describe the bug

Creating a conversation with lowercase address that is on the network causes an error to occur

### Expected behavior

Should create a conversation regardless of casing, Related web issue: https://github.com/xmtp/xmtp-js/issues/472

**Comment by nplasterer** [comment]
I recently learned that checksum addresses is an extra level of security https://eips.ethereum.org/EIPS/eip-55 which is why addresses created are neither all lowercase or all uppercase. We can't really control what they create a client with. The address form that is. So definitely some improvement on the sdk side to not error on casing.

**Comment by cameronvoell** [comment]
See comment here - https://github.com/xmtp/xmtp-react-native/pull/233#issuecomment-1922439276 Might want to check if this needs to be fixed for consent, deny function etc.

**Comment by alexrisch** [comment]
Included in version 1.26.0
