### ISSUE TITLE
Feature request: How can I get peer wallet address of conversation as v2?

### ISSUE THREAD

**Issue by hookie256** [xmtp/xmtp-react-native#572]

**Comment by nplasterer** [comment]
So in V3 we return a inboxId instead of an address. The inboxId can have an array of addresses associated with it. 

I'd recommend getting the address from the inboxId via this method https://github.com/xmtp/xmtp-react-native/blob/main/src/lib/Client.ts#L552-L568 The recoverAddress should be the address that they logged in first with.
