### ISSUE TITLE
[Bug] Reaction content types make message list error

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#93]
`ERROR in listBatchMessages [Error: The data couldn't be read because it isn't in the correct format.]`

`conversation.messages()` and `client.listBatchMessages()` error when the message is of content type reaction.

**Comment by dmccartney** [comment]
This looks like an issue with how the Android/iOS/JS SDK encode reactions.

Android and iOS agree to stuff the whole JSON blob of reaction fields into the `content` bytes.
But the JS SDK puts most of the reaction fields into the `parameters` mapping and only puts the reaction word into the `content` bytes.

[android encoding full JSON blob](https://github.com/xmtp/xmtp-android/blob/main/library/src/main/java/org/xmtp/android/library/codecs/ReactionCodec.kt#L35)
[iOS encoding full JSON blob](https://github.com/xmtp/xmtp-ios/blob/main/Sources/XMTP/Codecs/ReactionCodec.swift#L45)
[JS putting some fields into the parameters](https://github.com/xmtp/xmtp-js-content-types/blob/main/packages/content-type-reaction/src/Reaction.ts#L44-L51)

So this error is the iOS SDK puking on a reaction encoded by the JS SDK because it tries to parse the `content` bytes as JSON when instead it just contains the single reaction word:
```
// how JS encodes a "smile" reaction:
encoded = {
  type: ...,
  parameters: {
    encoding: "UTF-8",
    action: "added",
    reference: "...",
    schema: "shortcode"
  },
  content: [... 5 bytes...] // content string: "smile".toBytes()
}

// how iOS/Android (and thus RN) encode a "smile" reaction:
encoded = {
  type: ...,
  parameters: {}, // (empty)
  content: [... 100+ bytes ...] // json string: "{"action":"added","content":"smile",...}"
}
```

suggested TODO:
- [x] pick a canonical encoding (suggestion: JSON blob on `content`, a la iOS and Android)
- [x] make sure the reaction codec for all SDKs only encodes (sends) that form going forward
- [x] but also make sure the reaction codecs for all SDKs can decode (receive) either form for compat
